"""Generate a per-card effect table scaffold (SimOnPlay.g.cs) from cards.json.

The mod's resolver models a finite type surface. Every card is classified:

  FIELD    -- its effect is a flat field set (Damage/Block/Draw/Energy/HpLoss/Powers/15 core powers);
              the field-driven path in SimResolver handles it, so NO table entry is needed.
  BEHAVIOR -- its effect cannot be expressed as flat fields (X-cost, calculated/dynamic damage,
              exhaust synergy, summon/copy/transform, orb actions). These need a table entry that
              transcribes the card's OnPlay into the SimOnPlay DSL.

This script scans cards.json, classifies each card, and emits a C# table (`SimOnPlay.g.cs`) with one
entry per BEHAVIOR card, marked with the detected signal and a TODO to review/transcribe. Hand-filled
entries go into SimCardEffects.cs (which SimBuild consults). Run:

    python -m sim.gen_onplay [cards.json path] [out path]
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

# Behaviour signal detectors. These come from the game's var names + description text.
def signals(card: dict) -> list[str]:
    s: list[str] = []
    if card.get("is_x_cost") or card.get("is_x_star_cost"):
        s.append("x_cost")
    if card.get("star_cost"):
        s.append("star_cost")
    vars_ = card.get("vars") or {}
    var_keys = [k.lower() for k in vars_]
    if any(k.startswith("calculated") for k in var_keys):
        s.append("calculated_damage")
    if any(k.startswith("extradamage") for k in var_keys):
        s.append("dynamic_extra_damage")
    if any("summon" in k or "osty" in k or "forge" in k for k in var_keys):
        s.append("summon")
    desc = (card.get("description_raw") or card.get("description") or "").lower()
    for kw, tag in [
        ("exhaust", "exhaust_synergy"), ("consume", "consume"),
        ("summon", "summon"), ("copy", "copy"), ("transform", "transform"),
        ("random", "random"), ("channel", "orb"), ("evoke", "orb"),
        ("per card", "per_condition"), ("additional", "additional"),
    ]:
        # only take "per card" / "additional" as a signal when it's not a simple flat bonus
        if kw == "additional" and "additional damage for each" not in desc:
            continue
        if kw == "per card" and "for each card" not in desc:
            continue
        if kw in desc:
            s.append(tag)
    return s


def classify(card: dict) -> tuple[str, list[str]]:
    sg = signals(card)
    return ("BEHAVIOR", sg) if sg else ("FIELD", [])


def emit_gcs(cards: list[dict], out: Path) -> tuple[int, int]:
    field_n = 0
    behavior = []
    for c in cards:
        cls, sg = classify(c)
        if cls == "FIELD":
            field_n += 1
        else:
            behavior.append((c.get("id"), c.get("name"), sg))
    behavior.sort()

    lines = [
        "// AUTO-GENERATED by sim/gen_onplay.py — per-card effect table scaffold.",
        "// A BEHAVIOR card's effect is not a flat field set; it needs transcription into the SimOnPlay",
        "// DSL. Fill the Script/flags below (or move the entry to SimCardEffects.cs). Cards absent here",
        "// are FIELD cards handled by the field-driven path. Re-run gen_onplay.py to refresh.",
        "using System.Collections.Generic;",
        "namespace NekoComm.Game.Sim {",
        "    internal static class SimOnPlayG {",
        "        // id -> behaviour signals (for transcription).",
        "        public static readonly Dictionary<string,string[]> BehaviorSignals = new(System.StringComparer.OrdinalIgnoreCase) {",
    ]
    for cid, name, sg in behavior:
        info = ", ".join(f'"{x}"' for x in sg)
        lines.append(f'            ["{cid}"] = new[] {{ {info} }},   // {name}')
    lines.append("        };")
    lines.append("    }")
    lines.append("}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return field_n, len(behavior)


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    data_dir = Path(argv[0]) if len(argv) > 0 else Path("game_mod/mcp_server/data/eng")
    out = Path(argv[1]) if len(argv) > 1 else Path("game_mod/neko_comm/Game/Sim/SimOnPlay.g.cs")
    cards_path = data_dir / "cards.json"
    if not cards_path.exists():
        print(f"cards.json not found: {cards_path}")
        return 1
    cards = json.loads(cards_path.read_text(encoding="utf-8"))
    field_n, beh_n = emit_gcs(cards, out)
    print(f"cards.json: {len(cards)} cards")
    print(f"  FIELD     {field_n:4d} (field-driven path, no table entry)")
    print(f"  BEHAVIOR  {beh_n:4d} (need table entry / transcription)")
    print(f"wrote scaffold -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
