"""自动生成：全部 Power 的行为签名表（由 sim/gen_powers.py 生成，勿手改）。"""
POWER_TABLE = {
    'ACCELERANT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': []},
    'ACCURACY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageAdditive']},
    'ADAPTABLE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDeath', 'ShouldAllowHitting', 'ShouldStopCombatFromEnding', 'ShouldCreatureBeRemovedFromCombatAfterDeath', 'ShouldPowerBeRemovedAfterOwnerDeath']},
    'AFTERIMAGE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCardPlayed', 'AfterCardPlayed']},
    'AGGRESSION_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeSideTurnStart']},
    'AMBERGRIS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ShouldTakeExtraTurn', 'AfterTakingExtraTurn']},
    'ARSENAL_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardGeneratedForCombat']},
    'ARTIFACT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['TryModifyPowerAmountReceived', 'AfterModifyingPowerAmountReceived', 'GetScaledAmountForMultiplayer']},
    'ASLEEP_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageReceived', 'BeforeSideTurnEndVeryEarly', 'AfterSideTurnEnd']},
    'AUTOMATION_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardDrawn']},
    'BACK_ATTACK_LEFT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': []},
    'BACK_ATTACK_RIGHT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': []},
    'BARRICADE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'ShouldClearBlock']},
    'BATTLEWORN_DUMMY_TIME_LIMIT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnEnd']},
    'BEACON_OF_HOPE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterBlockGained']},
    'BIASED_COGNITION_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnStart']},
    'BLACK_HOLE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardPlayed', 'AfterStarsGained']},
    'BLOCK_NEXT_TURN_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterBlockCleared']},
    'BLUR_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ShouldClearBlock', 'AfterPreventingBlockClear', 'AfterSideTurnStart']},
    'BORROWED_TIME_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['TryModifyEnergyCostInCombat', 'AfterSideTurnEnd']},
    'BUFFER_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyHpLostAfterOstyLate', 'AfterModifyingHpLostAfterOsty', 'GetScaledAmountForMultiplayer']},
    'BURROWED_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ShouldClearBlock', 'AfterBlockBroken', 'AfterRemoved']},
    'BURST_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyCardPlayCount', 'AfterModifyingCardPlayCount', 'AfterSideTurnEnd']},
    'CACOPHONY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardDrawn']},
    'CALAMITY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCardPlayed', 'AfterCardPlayed']},
    'CALCIFY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageAdditive']},
    'CALL_OF_THE_VOID_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeHandDraw']},
    'CHAINS_OF_BINDING_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardDrawn', 'BeforeCardPlayed', 'ShouldPlay', 'BeforeSideTurnEnd']},
    'CHILD_OF_THE_STARS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterStarsSpent']},
    'CLARITY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyHandDraw', 'AfterSideTurnStart']},
    'COLOSSUS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageMultiplicative', 'AfterSideTurnEnd']},
    'CONCOCT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageGiven', 'AfterSideTurnEnd']},
    'CONFUSED_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardDrawn']},
    'CONQUEROR_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageMultiplicative', 'AfterSideTurnEnd']},
    'CONSTRICT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnEnd', 'AfterDeath']},
    'CONSUMING_SHADOW_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnEnd']},
    'COOLANT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnStart']},
    'CORROSIVE_WAVE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardDrawn', 'AfterSideTurnEnd']},
    'CORRUPTION_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['TryModifyEnergyCostInCombatLate', 'AfterModifyingCardPlayResultLocation']},
    'COUNTDOWN_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnStart']},
    'COVERED_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'AfterDeath', 'ModifyDamageMultiplicative', 'AfterSideTurnEnd']},
    'CRAB_RAGE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDeath']},
    'CREATIVE_AI_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeHandDraw']},
    'CRIMSON_MANTLE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterPlayerTurnStart']},
    'CRUELTY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': []},
    'CURIOUS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['TryModifyEnergyCostInCombat']},
    'CURL_UP_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageReceived', 'AfterCardPlayed']},
    'DAMPEN_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'AfterDeath', 'AfterRemoved']},
    'DANSE_MACABRE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCardPlayed']},
    'DARK_EMBRACE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardExhausted', 'AfterSideTurnEnd']},
    'DEBILITATE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnEnd']},
    'DEMESNE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyHandDraw', 'ModifyMaxEnergy']},
    'DEMISE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnEnd']},
    'DEMON_FORM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'AfterRemoved', 'AfterSideTurnStart']},
    'DEVOUR_LIFE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardPlayed']},
    'DEXTERITY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyBlockAdditive']},
    'DIE_FOR_YOU_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ShouldAllowHitting', 'ShouldCreatureBeRemovedFromCombatAfterDeath', 'ShouldPowerBeRemovedAfterOwnerDeath']},
    'DISINTEGRATION_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnEndLate']},
    'DOOM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeSideTurnEnd', 'AfterSideTurnEnd']},
    'DOUBLE_DAMAGE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageMultiplicative', 'AfterSideTurnEnd']},
    'DRAW_CARDS_NEXT_TURN_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyHandDraw', 'AfterSideTurnStart']},
    'DUPLICATION_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyCardPlayCount', 'AfterModifyingCardPlayCount', 'AfterSideTurnEnd']},
    'ECHO_FORM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'AfterRemoved', 'ModifyCardPlayCount', 'AfterModifyingCardPlayCount', 'AfterCardPlayed', 'BeforeSideTurnStart']},
    'ENERGY_NEXT_TURN_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterEnergyReset']},
    'ENRAGE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardPlayed']},
    'ENTROPY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterPlayerTurnStart']},
    'ENVENOM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageGiven']},
    'ESCAPE_ARTIST_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnEnd']},
    'FAN_OF_KNIVES_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': []},
    'FASTEN_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyBlockAdditive', 'AfterModifyingBlockAmount']},
    'FEEL_NO_PAIN_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardExhausted']},
    'FERAL_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'AfterModifyingCardPlayResultLocation', 'AfterSideTurnStart']},
    'FLAME_BARRIER_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageReceived', 'AfterSideTurnEnd']},
    'FLANKING_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'ModifyDamageMultiplicative', 'AfterSideTurnEnd']},
    'FLUTTER_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageMultiplicative', 'AfterDamageReceived']},
    'FOCUS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyOrbValue']},
    'FORBIDDEN_GRIMOIRE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCombatEnd']},
    'FOREGONE_CONCLUSION_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeHandDraw']},
    'FRAIL_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyBlockMultiplicative', 'AfterSideTurnEnd']},
    'FREE_ATTACK_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['TryModifyEnergyCostInCombatLate', 'BeforeCardPlayed']},
    'FREE_POWER_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['TryModifyEnergyCostInCombatLate', 'BeforeCardPlayed']},
    'FREE_SKILL_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['TryModifyEnergyCostInCombatLate', 'BeforeCardPlayed']},
    'FRIENDSHIP_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyMaxEnergy']},
    'FURNACE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnStart']},
    'GALVANIC_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCombatStart', 'AfterCardEnteredCombat', 'AfterCardPlayed']},
    'GENESIS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterEnergyReset']},
    'GIGANTIFICATION_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeAttack', 'ModifyDamageMultiplicative', 'AfterAttack']},
    'GRAVITY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCardPlayed', 'AfterCardPlayed', 'AfterSideTurnEnd']},
    'GUARDED_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'AfterDeath', 'ModifyDamageMultiplicative']},
    'HAILSTORM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeSideTurnEnd']},
    'HAMMER_TIME_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterForge']},
    'HANG_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageMultiplicative']},
    'HARD_TO_KILL_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageCap', 'AfterModifyingDamageAmount']},
    'HARDENED_SHELL_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyHpLostBeforeOstyLate', 'AfterModifyingHpLostBeforeOsty', 'AfterDamageReceived', 'BeforeSideTurnStart']},
    'HATCH_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnEnd']},
    'HAUNT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardPlayed']},
    'HEIST_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeDeath']},
    'HELLO_WORLD_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeHandDraw']},
    'HELLRAISER_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardDrawnEarly', 'AfterSideTurnEnd', 'BeforeAttack']},
    'HEX_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['TryModifyKeywordsInCombat', 'AfterApplied', 'AfterCardEnteredCombat', 'AfterDeath', 'AfterRemoved']},
    'HIBERNATE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterPlayerTurnStart']},
    'HIGH_VOLTAGE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnEnd']},
    'ILLUSION_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ShouldPowerBeRemovedOnDeath', 'AfterApplied', 'AfterDeath', 'ShouldAllowHitting', 'ShouldCreatureBeRemovedFromCombatAfterDeath', 'AfterCombatEnd']},
    'IMBALANCED_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageGiven']},
    'IMITATION_LEARNING_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCardPlayed', 'AfterCardPlayed']},
    'IMPROVEMENT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCombatEnd']},
    'INFERNO_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterPlayerTurnStart', 'AfterDamageReceived']},
    'INFESTED_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDeath', 'ShouldStopCombatFromEnding']},
    'INFINITE_BLADES_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeHandDraw']},
    'INTANGIBLE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyHpLostAfterOsty', 'AfterModifyingHpLostAfterOsty', 'ModifyDamageCap', 'AfterModifyingDamageAmount', 'AfterSideTurnEnd']},
    'INTERCEPT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageMultiplicative', 'AfterSideTurnEnd']},
    'ITERATION_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardDrawn']},
    'JUGGERNAUT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterBlockGained']},
    'JUGGLING_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'BeforeCardPlayed', 'AfterSideTurnEnd']},
    'KNOCKDOWN_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'ModifyDamageMultiplicative', 'AfterSideTurnEnd']},
    'LEADERSHIP_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageAdditive']},
    'LETHALITY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageMultiplicative']},
    'LIGHTNING_ROD_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterEnergyReset']},
    'LOOP_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterPlayerTurnStart']},
    'MACHINE_LEARNING_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyHandDraw']},
    'MAGIC_BOMB_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnEnd', 'AfterDeath']},
    'MASTER_PLANNER_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardPlayed']},
    'MAYHEM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterAutoPrePlayPhaseEntered']},
    'MIND_ROT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyHandDraw', 'AfterModifyingHandDraw']},
    'MINION_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ShouldPowerBeRemovedAfterOwnerDeath', 'ShouldOwnerDeathTriggerFatal']},
    'MONARCHS_GAZE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageGiven']},
    'MONOLOGUE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCardPlayed', 'AfterCardPlayed', 'AfterSideTurnEnd']},
    'NECRO_MASTERY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCurrentHpChanged']},
    'NEMESIS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnEnd']},
    'NEUROSURGE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnStart']},
    'NIGHTMARE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeHandDraw']},
    'NO_BLOCK_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnEnd', 'ModifyBlockMultiplicative']},
    'NO_DRAW_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ShouldDraw', 'AfterSideTurnEnd']},
    'NO_ENERGY_GAIN_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyEnergyGain', 'AfterModifyingEnergyGain', 'AfterSideTurnEnd']},
    'NOSTALGIA_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterModifyingCardPlayResultLocation']},
    'NOXIOUS_FUMES_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnStart']},
    'OBLIVION_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCardPlayed', 'AfterCardPlayed', 'AfterSideTurnEnd']},
    'ONE_FOR_ALL_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageAdditive']},
    'ONE_TWO_PUNCH_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyCardPlayCount', 'AfterModifyingCardPlayCount', 'AfterSideTurnEnd']},
    'ORBIT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterEnergySpent']},
    'PAGESTORM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardDrawn']},
    'PAINFUL_STABS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ShouldPowerBeRemovedAfterOwnerDeath', 'ShouldCreatureBeRemovedFromCombatAfterDeath', 'AfterAttack']},
    'PALE_BLUE_DOT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardPlayed', 'AfterSideTurnEnd']},
    'PANACHE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardPlayed', 'AfterSideTurnEnd']},
    'PAPER_CUTS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageGiven']},
    'PARRY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': []},
    'PERSONAL_HIVE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageReceived']},
    'PHANTOM_BLADES_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardEnteredCombat', 'AfterApplied', 'ModifyDamageAdditive']},
    'PILLAR_OF_CREATION_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardGeneratedForCombat']},
    'PLATING_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'BeforeSideTurnStart', 'BeforeSideTurnEndEarly', 'AfterSideTurnStart', 'GetScaledAmountForMultiplayer']},
    'PLOW_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageReceived']},
    'POISON_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnStart']},
    'POSSESS_SPEED_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterPowerAmountChanged', 'AfterDeath']},
    'POSSESS_STRENGTH_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterPowerAmountChanged', 'AfterDeath']},
    'PREP_TIME_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnStart']},
    'PYRE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyMaxEnergy']},
    'RADIANCE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterEnergyReset']},
    'RAGE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardPlayed', 'AfterSideTurnEnd']},
    'RAMPART_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnStart']},
    'RAVENOUS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDeath']},
    'REAPER_FORM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'AfterRemoved', 'AfterDamageGiven']},
    'REATTACH_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDeath', 'ShouldAllowHitting', 'ShouldCreatureBeRemovedFromCombatAfterDeath', 'ShouldPowerBeRemovedAfterOwnerDeath', 'ShouldOwnerDeathTriggerFatal']},
    'REBOUND_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterModifyingCardPlayResultLocation', 'AfterSideTurnEnd']},
    'REFLECT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageReceived', 'AfterSideTurnStart']},
    'REGEN_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeSideTurnEndEarly']},
    'RETAIN_HAND_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ShouldFlush', 'AfterSideTurnEnd']},
    'RINGING_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'AfterCardEnteredCombat', 'AfterSideTurnEnd', 'AfterRemoved', 'ShouldPlay']},
    'RITUAL_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'AfterSideTurnEnd']},
    'ROLLING_BOULDER_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterPlayerTurnStart']},
    'ROYALTIES_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCombatEnd']},
    'RUPTURE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCardPlayed', 'AfterDamageReceived', 'AfterCardPlayed']},
    'SANDPIT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'AfterSideTurnStartLate', 'AfterPowerAmountChanged', 'AfterRemoved', 'AfterCreatureAddedToCombat', 'AfterOstyRevived', 'BeforeSideTurnEnd']},
    'SEEKING_EDGE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': []},
    'SELF_FORMING_CLAY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterBlockCleared']},
    'SENTRY_MODE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeHandDraw']},
    'SERPENT_FORM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'AfterRemoved', 'BeforeCardPlayed', 'AfterCardPlayed']},
    'SHADOW_STEP_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnStart']},
    'SHADOWMELD_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyBlockMultiplicative', 'AfterSideTurnEnd']},
    'SHRIEK_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageReceived']},
    'SHRINK_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'AfterRemoved', 'AfterSideTurnEnd', 'AfterDeath', 'ModifyDamageMultiplicative']},
    'SHROUD_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterPowerAmountChanged']},
    'SIC_EM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageGiven', 'AfterSideTurnEnd']},
    'SIGNAL_BOOST_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyCardPlayCount', 'AfterModifyingCardPlayCount']},
    'SKITTISH_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterAttack', 'AfterSideTurnEnd', 'GetScaledAmountForMultiplayer']},
    'SLEIGHT_OF_FLESH_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterPowerAmountChanged']},
    'SLIPPERY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyHpLostAfterOsty', 'AfterDamageReceived', 'GetScaledAmountForMultiplayer']},
    'SLOTH_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ShouldPlay', 'BeforeCardPlayed', 'BeforeSideTurnStart']},
    'SLOW_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardPlayed', 'ModifyDamageMultiplicative', 'AfterModifyingDamageAmount', 'AfterSideTurnStart']},
    'SLUMBER_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageReceived', 'AfterRemoved', 'AfterSideTurnEnd']},
    'SMOGGY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardPlayed', 'AfterCardEnteredCombat', 'AfterSideTurnEnd', 'ShouldPlay']},
    'SMOKESTACK_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardGeneratedForCombat']},
    'SNEAKY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardPlayed']},
    'SOAR_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageMultiplicative']},
    'SOULBOUND_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardGeneratedForCombat']},
    'SPECTRUM_SHIFT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeHandDraw']},
    'SPEEDSTER_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardDrawn']},
    'SPINNER_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterEnergyReset']},
    'SPIRIT_OF_ASH_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCardPlayed']},
    'STAMPEDE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterAutoPostPlayPhaseEntered']},
    'STAR_NEXT_TURN_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterEnergyReset']},
    'STEAM_ERUPTION_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDeath', 'ShouldStopCombatFromEnding', 'ShouldCreatureBeRemovedFromCombatAfterDeath', 'ShouldPowerBeRemovedAfterOwnerDeath']},
    'STOCK_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDeath', 'ShouldStopCombatFromEnding']},
    'STORM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCardPlayed', 'AfterCardPlayed']},
    'STRANGLE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCardPlayed', 'AfterCardPlayed', 'AfterSideTurnEnd']},
    'STRATAGEM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterShuffle']},
    'STRENGTH_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageAdditive']},
    'SUBROUTINE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCardPlayed', 'AfterCardPlayed']},
    'SUCK_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterAttack']},
    'SUMMON_NEXT_TURN_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterPlayerTurnStart']},
    'SURPRISE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDeath', 'ShouldStopCombatFromEnding']},
    'SURROUNDED_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageMultiplicative', 'BeforeCardPlayed', 'BeforePotionUsed', 'AfterDeath']},
    'SWIPE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeDeath']},
    'SWORD_SAGE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterPowerAmountChanged', 'AfterCardEnteredCombat', 'AfterRemoved']},
    'TAG_TEAM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyCardPlayCount', 'AfterModifyingCardPlayCount']},
    'TAINTED_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageAdditive', 'AfterSideTurnEnd']},
    'TANGLED_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'AfterCardEnteredCombat', 'AfterSideTurnEnd', 'AfterRemoved', 'TryModifyEnergyCostInCombat']},
    'TANK_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'ModifyDamageMultiplicative']},
    'TEMPORARY_DEXTERITY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeApplied', 'AfterPowerAmountChanged', 'AfterSideTurnEnd']},
    'TEMPORARY_FOCUS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeApplied', 'AfterPowerAmountChanged', 'AfterSideTurnEnd']},
    'TEMPORARY_STRENGTH_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeApplied', 'AfterPowerAmountChanged', 'AfterSideTurnEnd']},
    'TENDER_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardPlayed', 'AfterSideTurnEnd']},
    'TERRITORIAL_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnEnd']},
    'THE_BOMB_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeSideTurnEnd']},
    'THE_GAMBIT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageReceived']},
    'THE_HUNT_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': []},
    'THE_SEALED_THRONE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCardPlayed']},
    'THIEVERY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': []},
    'THORNS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeDamageReceived']},
    'THUNDER_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterOrbEvoked']},
    'TOOLS_OF_THE_TRADE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyHandDraw', 'AfterPlayerTurnStart']},
    'TORIC_TOUGHNESS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterBlockCleared']},
    'TRACKING_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageMultiplicative']},
    'TRASH_TO_TREASURE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardGeneratedForCombat']},
    'TYRANNY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyHandDraw', 'AfterPlayerTurnStart']},
    'UNDERWORLD_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterDamageGiven', 'AfterSideTurnEnd']},
    'UNMOVABLE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyBlockMultiplicative']},
    'VEILPIERCER_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['TryModifyEnergyCostInCombatLate', 'BeforeCardPlayed']},
    'VICIOUS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterPowerAmountChanged']},
    'VIGOR_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeAttack', 'ModifyDamageAdditive', 'AfterAttack']},
    'VITAL_SPARK_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['BeforeCombatStart', 'AfterCardEnteredCombat', 'AfterCardPlayed', 'AfterRemoved', 'AfterPowerAmountChanged']},
    'VOID_FORM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterApplied', 'AfterRemoved', 'BeforePowerAmountChanged', 'BeforeApplied', 'TryModifyEnergyCostInCombatLate', 'TryModifyStarCost', 'AfterCardPlayed', 'BeforeSideTurnStart']},
    'VULNERABLE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageMultiplicative', 'AfterSideTurnEnd']},
    'WASTE_AWAY_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyMaxEnergy']},
    'WEAK_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ModifyDamageMultiplicative', 'AfterSideTurnEnd']},
    'WELL_LAID_PLANS_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['ShouldFlush']},
    'WITHERING_PRESENCE_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterCardPlayed']},
    'WRAITH_FORM_POWER': {'type': 'Buff', 'stack': 'Counter', 'hooks': ['AfterSideTurnStart']},
}