"""自动生成：战斗相关遗物的效果表（由 sim/gen_relics.py 生成，勿手改）。"""
RELIC_TABLE = {
    'AKABEKO': {'value': 0, 'var_type': '', 'hooks': ['AfterSideTurnStart']},
    'ALCHEMICAL_COFFER': {'value': 4, 'var_type': 'DynamicVar', 'hooks': ['AfterObtained']},
    'AMETHYST_AUBERGINE': {'value': 15, 'var_type': 'GoldVar', 'hooks': ['IsAllowed', 'TryModifyRewards', 'AfterModifyingRewards']},
    'ANCHOR': {'value': 10, 'var_type': 'BlockVar', 'hooks': ['BeforeCombatStart']},
    'ARCANE_SCROLL': {'value': 1, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'ARCHAIC_TOOTH': {'value': 0, 'var_type': 'StringVar', 'hooks': ['AfterCloned', 'AfterObtained']},
    'ART_OF_WAR': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['AfterCardPlayed', 'AfterSideTurnEnd', 'AfterEnergyReset', 'AfterCombatEnd']},
    'ASTROLABE': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'BAG_OF_MARBLES': {'value': 0, 'var_type': '', 'hooks': ['BeforeSideTurnStart']},
    'BAG_OF_PREPARATION': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['ModifyHandDraw']},
    'BEATING_REMNANT': {'value': 20, 'var_type': 'DynamicVar', 'hooks': ['ModifyHpLostAfterOsty', 'AfterModifyingHpLostAfterOsty', 'AfterDamageReceived', 'BeforeSideTurnStart']},
    'BEAUTIFUL_BRACELET': {'value': 4, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'BELLOWS': {'value': 0, 'var_type': '', 'hooks': ['AfterPlayerTurnStart']},
    'BELT_BUCKLE': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained', 'BeforeCombatStart', 'AfterCombatEnd', 'AfterPotionProcured', 'AfterPotionDiscarded', 'AfterPotionUsed', 'AfterCombatVictory']},
    'BIG_HAT': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['AfterSideTurnStart']},
    'BIG_MUSHROOM': {'value': 20, 'var_type': 'MaxHpVar', 'hooks': ['AfterObtained', 'AfterRoomEntered', 'ModifyHandDraw']},
    'BIIIG_HUG': {'value': 4, 'var_type': 'CardsVar', 'hooks': ['AfterObtained', 'AfterShuffle']},
    'BING_BONG': {'value': 0, 'var_type': '', 'hooks': ['AfterCardChangedPiles']},
    'BLACK_BLOOD': {'value': 12, 'var_type': 'HealVar', 'hooks': ['AfterCombatVictory']},
    'BLACK_STAR': {'value': 0, 'var_type': '', 'hooks': ['TryModifyRewards']},
    'BLESSED_ANTLER': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['ModifyMaxEnergy', 'BeforeHandDraw']},
    'BLOOD_SOAKED_ROSE': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['AfterObtained', 'ModifyMaxEnergy']},
    'BLOOD_VIAL': {'value': 2, 'var_type': 'HealVar', 'hooks': ['AfterPlayerTurnStartLate']},
    'BONE_FLUTE': {'value': 2, 'var_type': 'BlockVar', 'hooks': ['AfterAttack']},
    'BONE_TEA': {'value': 0, 'var_type': 'DynamicVar', 'hooks': ['AfterPlayerTurnStart']},
    'BOOK_OF_FIVE_RINGS': {'value': 5, 'var_type': 'CardsVar', 'hooks': ['IsAllowed', 'AfterCardChangedPiles']},
    'BOOK_REPAIR_KNIFE': {'value': 3, 'var_type': 'HealVar', 'hooks': ['AfterDiedToDoom']},
    'BOOKMARK': {'value': 0, 'var_type': '', 'hooks': ['AfterFlush']},
    'BOOMING_CONCH': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['ModifyHandDraw', 'AfterSideTurnStart']},
    'BOUND_PHYLACTERY': {'value': 1, 'var_type': 'SummonVar', 'hooks': ['BeforeCombatStart', 'AfterEnergyResetLate']},
    'BOWLER_HAT': {'value': 1, 'var_type': 'DynamicVar', 'hooks': ['IsAllowed', 'ModifyGoldGained', 'AfterModifyingGoldGained']},
    'BREAD': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['ModifyMaxEnergy', 'AfterSideTurnStart']},
    'BRILLIANT_SCARF': {'value': 5, 'var_type': 'CardsVar', 'hooks': ['TryModifyEnergyCostInCombatLate', 'TryModifyStarCost', 'BeforeSideTurnStart', 'AfterCardPlayed', 'AfterCombatEnd']},
    'BRIMSTONE': {'value': 0, 'var_type': '', 'hooks': ['AfterSideTurnStart']},
    'BRONZE_SCALES': {'value': 0, 'var_type': '', 'hooks': ['AfterRoomEntered']},
    'BURNING_BLOOD': {'value': 6, 'var_type': 'HealVar', 'hooks': ['AfterCombatVictory']},
    'BURNING_STICKS': {'value': 0, 'var_type': '', 'hooks': ['AfterRoomEntered', 'AfterCardExhausted', 'AfterCombatEnd']},
    'BYRDPIP': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained', 'BeforeCombatStart']},
    'CALLING_BELL': {'value': 3, 'var_type': 'DynamicVar', 'hooks': ['AfterObtained']},
    'CANDELABRA': {'value': 2, 'var_type': 'EnergyVar', 'hooks': ['AfterSideTurnStart']},
    'CAPTAINS_WHEEL': {'value': 18, 'var_type': 'BlockVar', 'hooks': ['AfterBlockCleared']},
    'CAULDRON': {'value': 5, 'var_type': 'DynamicVar', 'hooks': ['AfterObtained']},
    'CENTENNIAL_PUZZLE': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['AfterDamageReceived', 'AfterCombatEnd']},
    'CHANDELIER': {'value': 3, 'var_type': 'EnergyVar', 'hooks': ['AfterSideTurnStart']},
    'CHARONS_ASHES': {'value': 3, 'var_type': 'DamageVar', 'hooks': ['AfterCardExhausted']},
    'CHEMICAL_X': {'value': 2, 'var_type': 'DynamicVar', 'hooks': ['BeforeCardPlayed', 'ModifyXValue']},
    'CHOICES_PARADOX': {'value': 5, 'var_type': 'CardsVar', 'hooks': ['AfterPlayerTurnStart']},
    'CHOSEN_CHEESE': {'value': 1, 'var_type': 'MaxHpVar', 'hooks': ['AfterCombatEnd']},
    'CLAWS': {'value': 6, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'CLOAK_CLASP': {'value': 1, 'var_type': 'BlockVar', 'hooks': ['BeforeSideTurnEnd']},
    'CRACKED_CORE': {'value': 1, 'var_type': 'DynamicVar', 'hooks': ['BeforeSideTurnStart']},
    'CROSSBOW': {'value': 0, 'var_type': '', 'hooks': ['AfterSideTurnStart']},
    'CURSED_PEARL': {'value': 333, 'var_type': 'GoldVar', 'hooks': ['AfterObtained']},
    'DARKSTONE_PERIAPT': {'value': 6, 'var_type': 'MaxHpVar', 'hooks': ['AfterCardChangedPiles']},
    'DATA_DISK': {'value': 0, 'var_type': '', 'hooks': ['AfterRoomEntered']},
    'DAUGHTER_OF_THE_WIND': {'value': 1, 'var_type': 'BlockVar', 'hooks': ['AfterCardPlayed']},
    'DELICATE_FROND': {'value': 0, 'var_type': '', 'hooks': ['BeforeCombatStart']},
    'DEMON_TONGUE': {'value': 0, 'var_type': '', 'hooks': ['AfterDamageReceived', 'BeforeSideTurnStart']},
    'DIAMOND_DIADEM': {'value': 20, 'var_type': 'BlockVar', 'hooks': ['AfterSideTurnStart']},
    'DISTINGUISHED_CAPE': {'value': 2, 'var_type': 'DynamicVar', 'hooks': ['AfterObtained']},
    'DIVINE_DESTINY': {'value': 7, 'var_type': 'StarsVar', 'hooks': ['AfterSideTurnStart']},
    'DIVINE_RIGHT': {'value': 3, 'var_type': 'StarsVar', 'hooks': ['AfterRoomEntered']},
    'DOLLYS_MIRROR': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'DOWSING_ROD': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'DRAGON_FRUIT': {'value': 1, 'var_type': 'MaxHpVar', 'hooks': ['IsAllowed', 'AfterGoldGained']},
    'DREAM_CATCHER': {'value': 0, 'var_type': '', 'hooks': ['TryModifyRestSiteHealRewards']},
    'DRIFTWOOD': {'value': 0, 'var_type': '', 'hooks': ['TryModifyRewardsLate']},
    'DUSTY_TOME': {'value': 0, 'var_type': 'StringVar', 'hooks': ['AfterObtained']},
    'ECTOPLASM': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['ModifyGoldGained', 'AfterModifyingGoldGained', 'ModifyMaxEnergy']},
    'ELECTRIC_SHRYMP': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'EMBER_TEA': {'value': 0, 'var_type': 'DynamicVar', 'hooks': ['AfterRoomEntered']},
    'EMOTION_CHIP': {'value': 0, 'var_type': '', 'hooks': ['AfterDamageReceived', 'AfterPlayerTurnStart', 'AfterCombatEnd']},
    'EMPTY_CAGE': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'ETERNAL_FEATHER': {'value': 5, 'var_type': 'CardsVar', 'hooks': ['AfterRoomEntered']},
    'FAKE_ANCHOR': {'value': 4, 'var_type': 'BlockVar', 'hooks': ['BeforeCombatStart']},
    'FAKE_BLOOD_VIAL': {'value': 1, 'var_type': 'HealVar', 'hooks': ['AfterPlayerTurnStartLate']},
    'FAKE_HAPPY_FLOWER': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['AfterSideTurnStart', 'AfterCombatEnd']},
    'FAKE_LEES_WAFFLE': {'value': 10, 'var_type': 'HealVar', 'hooks': ['AfterObtained']},
    'FAKE_MANGO': {'value': 3, 'var_type': 'MaxHpVar', 'hooks': ['AfterObtained']},
    'FAKE_ORICHALCUM': {'value': 3, 'var_type': 'BlockVar', 'hooks': ['BeforeSideTurnEndVeryEarly', 'BeforeSideTurnEnd', 'BeforeSideTurnStart']},
    'FAKE_SNECKO_EYE': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained', 'BeforeCombatStart']},
    'FAKE_STRIKE_DUMMY': {'value': 1, 'var_type': 'DynamicVar', 'hooks': ['ModifyDamageAdditive']},
    'FAKE_VENERABLE_TEA_SET': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['AfterRoomEntered', 'AfterEnergyReset']},
    'FENCING_MANUAL': {'value': 10, 'var_type': 'ForgeVar', 'hooks': ['AfterSideTurnStart']},
    'FESTIVE_POPPER': {'value': 9, 'var_type': 'DamageVar', 'hooks': ['AfterPlayerTurnStart']},
    'FIDDLE': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['ModifyHandDraw', 'ShouldDraw', 'AfterPreventingDraw']},
    'FISHING_ROD': {'value': 3, 'var_type': 'DynamicVar', 'hooks': ['AfterCombatEnd']},
    'FORGOTTEN_SOUL': {'value': 1, 'var_type': 'DamageVar', 'hooks': ['AfterCardExhausted']},
    'FRAGRANT_MUSHROOM': {'value': 15, 'var_type': 'HpLossVar', 'hooks': ['AfterObtained']},
    'FRESNEL_LENS': {'value': 2, 'var_type': 'DynamicVar', 'hooks': ['TryModifyCardRewardOptionsLate', 'ModifyMerchantCardCreationResults', 'TryModifyCardBeingAddedToDeck']},
    'FROZEN_EGG': {'value': 0, 'var_type': '', 'hooks': ['IsAllowed', 'TryModifyCardRewardOptionsLate', 'ModifyMerchantCardCreationResults', 'TryModifyCardBeingAddedToDeck']},
    'FUNERARY_MASK': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['BeforeHandDraw']},
    'FUR_COAT': {'value': 8, 'var_type': 'DynamicVar', 'hooks': ['AfterObtained', 'BeforeCombatStart', 'AfterCreatureAddedToCombat']},
    'GALACTIC_DUST': {'value': 10, 'var_type': 'StarsVar', 'hooks': ['AfterStarsSpent']},
    'GAMBLING_CHIP': {'value': 0, 'var_type': '', 'hooks': ['AfterPlayerTurnStart']},
    'GAME_PIECE': {'value': 1, 'var_type': 'CardsVar', 'hooks': ['AfterCardPlayed']},
    'GHOST_SEED': {'value': 0, 'var_type': '', 'hooks': ['AfterCardEnteredCombat', 'AfterRoomEntered']},
    'GIRYA': {'value': 0, 'var_type': '', 'hooks': ['IsAllowed', 'AfterRoomEntered', 'TryModifyRestSiteOptions']},
    'GLASS_EYE': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'GLITTER': {'value': 0, 'var_type': '', 'hooks': ['TryModifyCardRewardOptionsLate']},
    'GNARLED_HAMMER': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'GOLD_PLATED_CABLES': {'value': 0, 'var_type': '', 'hooks': ['ModifyOrbPassiveTriggerCounts', 'AfterModifyingOrbPassiveTriggerCount']},
    'GOLDEN_COMPASS': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'GOLDEN_PEARL': {'value': 150, 'var_type': 'GoldVar', 'hooks': ['AfterObtained']},
    'GORGET': {'value': 0, 'var_type': '', 'hooks': ['AfterRoomEntered']},
    'GREMLIN_HORN': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['AfterDeath']},
    'HAND_DRILL': {'value': 0, 'var_type': '', 'hooks': ['AfterBlockBroken']},
    'HAPPY_FLOWER': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['AfterSideTurnStart', 'AfterCombatEnd']},
    'HEFTY_TABLET': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'HELICAL_DART': {'value': 0, 'var_type': '', 'hooks': ['AfterCardPlayed']},
    'HISTORY_COURSE': {'value': 0, 'var_type': '', 'hooks': ['AfterAutoPrePlayPhaseEntered']},
    'HORN_CLEAT': {'value': 14, 'var_type': 'BlockVar', 'hooks': ['AfterBlockCleared']},
    'ICE_CREAM': {'value': 0, 'var_type': '', 'hooks': ['ShouldPlayerResetEnergy']},
    'INFUSED_CORE': {'value': 3, 'var_type': 'DynamicVar', 'hooks': ['AfterSideTurnStart', 'ModifyOrbValue']},
    'INTIMIDATING_HELMET': {'value': 4, 'var_type': 'BlockVar', 'hooks': ['BeforeCardPlayed']},
    'IRON_CLUB': {'value': 4, 'var_type': 'CardsVar', 'hooks': ['AfterCardPlayed']},
    'IVORY_TILE': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['AfterCardPlayed']},
    'JEWELED_MASK': {'value': 0, 'var_type': '', 'hooks': ['BeforeHandDraw']},
    'JEWELRY_BOX': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'JOSS_PAPER': {'value': 5, 'var_type': 'DynamicVar', 'hooks': ['AfterCardExhausted', 'AfterSideTurnEnd', 'AfterCombatEnd']},
    'JUZU_BRACELET': {'value': 0, 'var_type': '', 'hooks': ['IsAllowed']},
    'KALEIDOSCOPE': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['IsAllowedAtNeow', 'AfterObtained']},
    'KIFUDA': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'KUNAI': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['BeforeSideTurnStart', 'AfterCardPlayed', 'AfterCombatEnd']},
    'KUSARIGAMA': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['BeforeCombatStart', 'AfterSideTurnEnd', 'AfterCardPlayed', 'AfterCombatEnd']},
    'LANTERN': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['AfterSideTurnStart']},
    'LARGE_CAPSULE': {'value': 2, 'var_type': 'IntVar', 'hooks': ['AfterObtained']},
    'LASTING_CANDY': {'value': 0, 'var_type': '', 'hooks': ['IsAllowed', 'TryModifyCardRewardOptions', 'BeforeCombatRewardOffered']},
    'LAVA_LAMP': {'value': 0, 'var_type': '', 'hooks': ['AfterRoomEntered', 'AfterDamageReceived', 'TryModifyCardRewardOptionsLate']},
    'LAVA_ROCK': {'value': 2, 'var_type': 'DynamicVar', 'hooks': ['TryModifyRewards']},
    'LEAD_PAPERWEIGHT': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'LEAFY_POULTICE': {'value': 12, 'var_type': 'MaxHpVar', 'hooks': ['AfterObtained']},
    'LEES_WAFFLE': {'value': 7, 'var_type': 'MaxHpVar', 'hooks': ['AfterObtained']},
    'LETTER_OPENER': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['BeforeCombatStart', 'AfterSideTurnStart', 'AfterCardPlayed', 'AfterCombatEnd']},
    'LIZARD_TAIL': {'value': 50, 'var_type': 'HealVar', 'hooks': ['ShouldDieLate', 'AfterPreventingDeath']},
    'LOOMING_FRUIT': {'value': 31, 'var_type': 'MaxHpVar', 'hooks': ['AfterObtained']},
    'LORDS_PARASOL': {'value': 0, 'var_type': '', 'hooks': ['AfterRoomEntered']},
    'LOST_COFFER': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'LOST_WISP': {'value': 8, 'var_type': 'DamageVar', 'hooks': ['AfterCardPlayed']},
    'LUCKY_FYSH': {'value': 15, 'var_type': 'GoldVar', 'hooks': ['IsAllowed', 'AfterCardChangedPiles']},
    'LUNAR_PASTRY': {'value': 1, 'var_type': 'StarsVar', 'hooks': ['AfterSideTurnEnd']},
    'MANGO': {'value': 14, 'var_type': 'MaxHpVar', 'hooks': ['AfterObtained']},
    'MASSIVE_SCROLL': {'value': 0, 'var_type': '', 'hooks': ['IsAllowed', 'AfterObtained']},
    'MAW_BANK': {'value': 12, 'var_type': 'GoldVar', 'hooks': ['AfterRoomEntered', 'AfterItemPurchased']},
    'MEAL_TICKET': {'value': 15, 'var_type': 'HealVar', 'hooks': ['IsAllowed', 'AfterRoomEntered']},
    'MEAT_CLEAVER': {'value': 0, 'var_type': '', 'hooks': ['TryModifyRestSiteOptions']},
    'MEAT_ON_THE_BONE': {'value': 50, 'var_type': 'DynamicVar', 'hooks': ['BeforeCombatStart', 'AfterCurrentHpChanged', 'AfterCombatVictoryEarly']},
    'MEMBERSHIP_CARD': {'value': 50, 'var_type': 'DynamicVar', 'hooks': ['ModifyMerchantPrice']},
    'MERCURY_HOURGLASS': {'value': 3, 'var_type': 'DamageVar', 'hooks': ['AfterPlayerTurnStart']},
    'METRONOME': {'value': 30, 'var_type': 'DamageVar', 'hooks': ['AfterRoomEntered', 'AfterOrbChanneled', 'AfterCombatEnd']},
    'MINI_REGENT': {'value': 0, 'var_type': '', 'hooks': ['AfterStarsSpent', 'BeforeSideTurnStart', 'AfterCombatEnd']},
    'MINIATURE_CANNON': {'value': 3, 'var_type': 'DynamicVar', 'hooks': ['ModifyDamageAdditive']},
    'MINIATURE_TENT': {'value': 0, 'var_type': '', 'hooks': ['ShouldDisableRemainingRestSiteOptions']},
    'MOLTEN_EGG': {'value': 0, 'var_type': '', 'hooks': ['IsAllowed', 'TryModifyCardRewardOptionsLate', 'ModifyMerchantCardCreationResults', 'TryModifyCardBeingAddedToDeck']},
    'MR_STRUGGLES': {'value': 0, 'var_type': '', 'hooks': ['AfterPlayerTurnStart']},
    'MUMMIFIED_HAND': {'value': 0, 'var_type': '', 'hooks': ['AfterCardPlayed']},
    'MUSIC_BOX': {'value': 0, 'var_type': '', 'hooks': ['BeforeCardPlayed', 'AfterCardPlayed', 'BeforeSideTurnStart', 'AfterCombatEnd']},
    'MYSTIC_LIGHTER': {'value': 9, 'var_type': 'DamageVar', 'hooks': ['ModifyDamageAdditive']},
    'NEOWS_BONES': {'value': 2, 'var_type': 'DynamicVar', 'hooks': ['AfterObtained']},
    'NEOWS_SACRIFICE': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'NEOWS_TALISMAN': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'NEOWS_TORMENT': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'NEW_LEAF': {'value': 1, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'NINJA_SCROLL': {'value': 3, 'var_type': 'DynamicVar', 'hooks': ['BeforeHandDraw']},
    'NUNCHAKU': {'value': 10, 'var_type': 'CardsVar', 'hooks': ['AfterCardPlayed']},
    'NUTRITIOUS_OYSTER': {'value': 11, 'var_type': 'MaxHpVar', 'hooks': ['AfterObtained']},
    'NUTRITIOUS_SOUP': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'ODDLY_SMOOTH_STONE': {'value': 0, 'var_type': '', 'hooks': ['AfterRoomEntered']},
    'OLD_COIN': {'value': 300, 'var_type': 'GoldVar', 'hooks': ['IsAllowed', 'AfterObtained']},
    'ORANGE_DOUGH': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['AfterSideTurnStart']},
    'ORICHALCUM': {'value': 6, 'var_type': 'BlockVar', 'hooks': ['BeforeSideTurnEndVeryEarly', 'BeforeSideTurnEnd', 'BeforeSideTurnStart']},
    'ORNAMENTAL_FAN': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['BeforeSideTurnStart', 'AfterCardPlayed', 'AfterCombatEnd']},
    'ORRERY': {'value': 5, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'PAELS_BLOOD': {'value': 1, 'var_type': 'CardsVar', 'hooks': ['ModifyHandDraw']},
    'PAELS_CLAW': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'PAELS_EYE': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained', 'BeforeCardPlayed', 'AfterSideTurnStart', 'ShouldTakeExtraTurn', 'BeforeSideTurnEndEarly', 'AfterTakingExtraTurn', 'AfterCombatEnd']},
    'PAELS_FLESH': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['ModifyMaxEnergy', 'BeforeCombatStart', 'BeforeSideTurnStart', 'AfterSideTurnStart', 'AfterCombatEnd']},
    'PAELS_GROWTH': {'value': 0, 'var_type': 'StringVar', 'hooks': ['AfterObtained', 'TryModifyRestSiteOptions']},
    'PAELS_HORN': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'PAELS_LEGION': {'value': 2, 'var_type': 'DynamicVar', 'hooks': ['AfterObtained', 'BeforeCombatStart', 'ModifyBlockMultiplicative', 'AfterModifyingBlockAmount', 'AfterCardPlayed', 'AfterSideTurnStart', 'AfterCombatEnd']},
    'PAELS_TEARS': {'value': 2, 'var_type': 'EnergyVar', 'hooks': ['BeforeSideTurnEnd', 'AfterSideTurnStart', 'AfterCombatEnd']},
    'PAELS_TOOTH': {'value': 5, 'var_type': 'CardsVar', 'hooks': ['AfterCloned', 'AfterObtained', 'AfterCombatEnd']},
    'PAELS_WING': {'value': 2, 'var_type': 'DynamicVar', 'hooks': ['TryModifyCardRewardAlternatives']},
    'PANDORAS_BOX': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'PANTOGRAPH': {'value': 25, 'var_type': 'HealVar', 'hooks': ['AfterRoomEntered', 'BeforeCombatStart']},
    'PARRYING_SHIELD': {'value': 10, 'var_type': 'BlockVar', 'hooks': ['AfterSideTurnEnd']},
    'PEAR': {'value': 10, 'var_type': 'MaxHpVar', 'hooks': ['AfterObtained']},
    'PEN_NIB': {'value': 0, 'var_type': '', 'hooks': ['ModifyDamageMultiplicative', 'BeforeCardPlayed', 'AfterCardPlayed']},
    'PENDULUM': {'value': 1, 'var_type': 'CardsVar', 'hooks': ['BeforeHandDraw', 'ModifyHandDraw', 'AfterCombatEnd']},
    'PERMAFROST': {'value': 7, 'var_type': 'BlockVar', 'hooks': ['AfterRoomEntered', 'AfterCardPlayed']},
    'PETRIFIED_TOAD': {'value': 0, 'var_type': '', 'hooks': ['BeforeCombatStartLate']},
    'PHIAL_HOLSTER': {'value': 1, 'var_type': 'DynamicVar', 'hooks': ['AfterObtained']},
    'PHILOSOPHERS_STONE': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['ModifyMaxEnergy', 'AfterCreatureAddedToCombat', 'AfterRoomEntered']},
    'PHYLACTERY_UNBOUND': {'value': 5, 'var_type': 'SummonVar', 'hooks': ['BeforeCombatStart', 'AfterSideTurnStart']},
    'PLANISPHERE': {'value': 5, 'var_type': 'HealVar', 'hooks': ['IsAllowed', 'AfterRoomEntered']},
    'POCKETWATCH': {'value': 3, 'var_type': 'DynamicVar', 'hooks': ['AfterCardPlayed', 'ModifyHandDraw', 'AfterModifyingHandDraw', 'BeforeSideTurnStart', 'AfterSideTurnStart', 'AfterCombatEnd']},
    'POLLINOUS_CORE': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['BeforeHandDraw', 'AfterCombatEnd', 'ModifyHandDraw', 'AfterModifyingHandDraw']},
    'POMANDER': {'value': 1, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'POTION_BELT': {'value': 2, 'var_type': 'DynamicVar', 'hooks': ['AfterObtained']},
    'POWER_CELL': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['BeforeSideTurnStart']},
    'PRAYER_WHEEL': {'value': 0, 'var_type': '', 'hooks': ['TryModifyRewards']},
    'PRECARIOUS_SHEARS': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'PRECISE_SCISSORS': {'value': 1, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'PRESERVED_FOG': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'PRISMATIC_GEM': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['ModifyMaxEnergy']},
    'PUMPKIN_CANDLE': {'value': 5, 'var_type': 'DynamicVar', 'hooks': ['AfterObtained', 'ModifyMaxEnergy', 'AfterCombatEnd', 'TryModifyRestSiteOptions']},
    'PUNCH_DAGGER': {'value': 5, 'var_type': 'DynamicVar', 'hooks': ['AfterObtained']},
    'RADIANT_PEARL': {'value': 1, 'var_type': 'CardsVar', 'hooks': ['BeforeHandDraw']},
    'RAINBOW_RING': {'value': 0, 'var_type': '', 'hooks': ['BeforeSideTurnStart', 'AfterCardPlayed', 'AfterCombatEnd']},
    'RAZOR_TOOTH': {'value': 0, 'var_type': '', 'hooks': ['AfterCardPlayed']},
    'RED_MASK': {'value': 0, 'var_type': '', 'hooks': ['BeforeSideTurnStart']},
    'RED_SKULL': {'value': 50, 'var_type': 'DynamicVar', 'hooks': ['AfterRoomEntered', 'AfterCombatEnd', 'AfterCurrentHpChanged']},
    'REGAL_PILLOW': {'value': 15, 'var_type': 'HealVar', 'hooks': ['ModifyRestSiteHealAmount', 'AfterRestSiteHeal', 'AfterRoomEntered']},
    'REGALITE': {'value': 4, 'var_type': 'BlockVar', 'hooks': ['AfterCardGeneratedForCombat', 'BeforeSideTurnStart', 'AfterCombatEnd']},
    'REPTILE_TRINKET': {'value': 0, 'var_type': '', 'hooks': ['AfterPotionUsed']},
    'RING_OF_THE_DRAKE': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['ModifyHandDraw']},
    'RING_OF_THE_SNAKE': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['ModifyHandDraw']},
    'RINGING_TRIANGLE': {'value': 0, 'var_type': '', 'hooks': ['ShouldFlush']},
    'RIPPLE_BASIN': {'value': 4, 'var_type': 'BlockVar', 'hooks': ['BeforeSideTurnEnd', 'AfterCardPlayed', 'BeforeSideTurnStart', 'AfterCombatEnd']},
    'ROYAL_POISON': {'value': 4, 'var_type': 'DamageVar', 'hooks': ['AfterPlayerTurnStart']},
    'ROYAL_STAMP': {'value': 1, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'RUINED_HELMET': {'value': 0, 'var_type': '', 'hooks': ['TryModifyPowerAmountReceived', 'AfterModifyingPowerAmountReceived', 'AfterCombatEnd']},
    'RUNIC_CAPACITOR': {'value': 3, 'var_type': 'RepeatVar', 'hooks': ['AfterSideTurnStart']},
    'RUNIC_PYRAMID': {'value': 0, 'var_type': '', 'hooks': ['ShouldFlush']},
    'SAI': {'value': 7, 'var_type': 'BlockVar', 'hooks': ['AfterSideTurnStart']},
    'SAND_CASTLE': {'value': 6, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'SCREAMING_FLAGON': {'value': 20, 'var_type': 'DamageVar', 'hooks': ['BeforeSideTurnEnd']},
    'SCROLL_BOXES': {'value': 0, 'var_type': '', 'hooks': ['IsAllowedAtNeow', 'AfterObtained']},
    'SEA_GLASS': {'value': 15, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'SEAL_OF_GOLD': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['AfterSideTurnStart']},
    'SELF_FORMING_CLAY': {'value': 3, 'var_type': 'DynamicVar', 'hooks': ['AfterDamageReceived']},
    'SERE_TALON': {'value': 9, 'var_type': 'HpLossVar', 'hooks': ['AfterObtained']},
    'SHOVEL': {'value': 0, 'var_type': '', 'hooks': ['IsAllowed', 'TryModifyRestSiteOptions']},
    'SHURIKEN': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['BeforeSideTurnStart', 'AfterCardPlayed', 'AfterCombatEnd']},
    'SIGNET_RING': {'value': 888, 'var_type': 'GoldVar', 'hooks': ['AfterObtained']},
    'SILKEN_TRESS': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained', 'TryModifyCardRewardOptionsLate', 'AfterModifyingCardRewardOptions']},
    'SILVER_CRUCIBLE': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['IsAllowed', 'TryModifyCardRewardOptionsLate', 'AfterModifyingCardRewardOptions', 'AfterRoomEntered', 'ShouldGenerateTreasure']},
    'SLING_OF_COURAGE': {'value': 0, 'var_type': '', 'hooks': ['AfterRoomEntered']},
    'SMALL_CAPSULE': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'SNECKO_EYE': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['AfterObtained', 'BeforeCombatStart', 'ModifyHandDraw']},
    'SNECKO_SKULL': {'value': 0, 'var_type': '', 'hooks': ['ModifyPowerAmountGivenAdditive', 'AfterModifyingPowerAmountGiven']},
    'SOZU': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['ShouldProcurePotion', 'ModifyMaxEnergy']},
    'SPARKLING_ROUGE': {'value': 0, 'var_type': '', 'hooks': ['AfterBlockCleared']},
    'SPIKED_GAUNTLETS': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['ModifyMaxEnergy', 'TryModifyEnergyCostInCombat']},
    'STONE_CALENDAR': {'value': 52, 'var_type': 'DamageVar', 'hooks': ['AfterSideTurnStart', 'BeforeSideTurnEnd', 'AfterCombatEnd', 'AfterRoomEntered']},
    'STONE_CRACKER': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['AfterRoomEntered']},
    'STONE_HUMIDIFIER': {'value': 5, 'var_type': 'MaxHpVar', 'hooks': ['AfterRestSiteHeal']},
    'STORYBOOK': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'STRAWBERRY': {'value': 7, 'var_type': 'MaxHpVar', 'hooks': ['AfterObtained']},
    'STRIKE_DUMMY': {'value': 3, 'var_type': 'DynamicVar', 'hooks': ['ModifyDamageAdditive']},
    'STURDY_CLAMP': {'value': 10, 'var_type': 'BlockVar', 'hooks': ['ShouldClearBlock', 'AfterPreventingBlockClear']},
    'SWORD_OF_JADE': {'value': 0, 'var_type': '', 'hooks': ['AfterRoomEntered']},
    'SWORD_OF_STONE': {'value': 5, 'var_type': 'DynamicVar', 'hooks': ['AfterCombatVictory']},
    'SYMBIOTIC_VIRUS': {'value': 1, 'var_type': 'DynamicVar', 'hooks': ['AfterSideTurnStart']},
    'TANXS_WHISTLE': {'value': 0, 'var_type': '', 'hooks': ['AfterObtained']},
    'TEA_OF_DISCOURTESY': {'value': 1, 'var_type': 'HealVar', 'hooks': ['BeforeCombatStart']},
    'THE_ABACUS': {'value': 6, 'var_type': 'BlockVar', 'hooks': ['AfterShuffle']},
    'THE_BOOT': {'value': 5, 'var_type': 'DynamicVar', 'hooks': ['ModifyHpLostAfterOstyLate', 'AfterModifyingHpLostAfterOsty']},
    'THE_COURIER': {'value': 20, 'var_type': 'DynamicVar', 'hooks': ['ModifyMerchantPrice', 'ShouldRefillMerchantEntry']},
    'THROWING_AXE': {'value': 0, 'var_type': '', 'hooks': ['AfterRoomEntered', 'ModifyCardPlayCount', 'AfterModifyingCardPlayCount', 'AfterCombatEnd']},
    'TINGSHA': {'value': 3, 'var_type': 'DamageVar', 'hooks': ['AfterCardDiscarded']},
    'TINY_MAILBOX': {'value': 0, 'var_type': '', 'hooks': ['TryModifyRestSiteHealRewards']},
    'TOASTY_MITTENS': {'value': 0, 'var_type': '', 'hooks': ['AfterPlayerTurnStart']},
    'TOOLBOX': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['BeforeHandDraw']},
    'TOUCH_OF_OROBAS': {'value': 0, 'var_type': 'StringVar', 'hooks': ['AfterCloned', 'AfterObtained']},
    'TOUGH_BANDAGES': {'value': 3, 'var_type': 'BlockVar', 'hooks': ['AfterCardDiscarded']},
    'TOXIC_EGG': {'value': 0, 'var_type': '', 'hooks': ['IsAllowed', 'TryModifyCardRewardOptionsLate', 'ModifyMerchantCardCreationResults', 'TryModifyCardBeingAddedToDeck']},
    'TOY_BOX': {'value': 5, 'var_type': 'DynamicVar', 'hooks': ['AfterObtained', 'AfterCombatEnd']},
    'TRI_BOOMERANG': {'value': 3, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'TUNGSTEN_ROD': {'value': 1, 'var_type': 'DynamicVar', 'hooks': ['ModifyHpLostAfterOsty', 'AfterModifyingHpLostAfterOsty']},
    'TUNING_FORK': {'value': 10, 'var_type': 'CardsVar', 'hooks': ['AfterCardPlayed']},
    'TWISTED_FUNNEL': {'value': 0, 'var_type': '', 'hooks': ['BeforeSideTurnStart']},
    'UNCEASING_TOP': {'value': 0, 'var_type': '', 'hooks': ['AfterHandEmptied']},
    'UNDYING_SIGIL': {'value': 0, 'var_type': 'DynamicVar', 'hooks': ['ModifyDamageMultiplicative']},
    'UNSETTLING_LAMP': {'value': 0, 'var_type': '', 'hooks': ['BeforeCombatStart', 'BeforePowerAmountChanged', 'ModifyPowerAmountGivenMultiplicative', 'AfterCardPlayed', 'AfterCombatEnd']},
    'VAJRA': {'value': 0, 'var_type': '', 'hooks': ['AfterRoomEntered']},
    'VAMBRACE': {'value': 0, 'var_type': '', 'hooks': ['BeforeCombatStart', 'ModifyBlockMultiplicative', 'AfterModifyingBlockAmount', 'AfterCardPlayed', 'AfterCombatEnd']},
    'VELVET_CHOKER': {'value': 6, 'var_type': 'CardsVar', 'hooks': ['ModifyMaxEnergy', 'ShouldPlay', 'AfterCardPlayed', 'AfterRoomEntered', 'AfterCombatEnd', 'BeforeSideTurnStart']},
    'VENERABLE_TEA_SET': {'value': 2, 'var_type': 'EnergyVar', 'hooks': ['AfterRoomEntered', 'AfterEnergyReset']},
    'VERY_HOT_COCOA': {'value': 4, 'var_type': 'EnergyVar', 'hooks': ['AfterSideTurnStart']},
    'VEXING_PUZZLEBOX': {'value': 0, 'var_type': '', 'hooks': ['AfterPlayerTurnStart']},
    'VITRUVIAN_MINION': {'value': 0, 'var_type': '', 'hooks': ['ModifyDamageMultiplicative', 'ModifyBlockMultiplicative']},
    'WAR_HAMMER': {'value': 4, 'var_type': 'CardsVar', 'hooks': ['AfterCombatVictory']},
    'WAR_PAINT': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'WHETSTONE': {'value': 2, 'var_type': 'CardsVar', 'hooks': ['AfterObtained']},
    'WHISPERING_EARRING': {'value': 1, 'var_type': 'EnergyVar', 'hooks': ['ModifyMaxEnergy', 'AfterAutoPrePlayPhaseEnteredLate']},
    'WHITE_BEAST_STATUE': {'value': 0, 'var_type': '', 'hooks': ['IsAllowed', 'ShouldForcePotionReward']},
    'WHITE_STAR': {'value': 0, 'var_type': '', 'hooks': ['IsAllowed', 'TryModifyRewards']},
    'WING_CHARM': {'value': 1, 'var_type': 'DynamicVar', 'hooks': ['TryModifyCardRewardOptionsLate']},
    'WINGED_BOOTS': {'value': 3, 'var_type': 'DynamicVar', 'hooks': ['IsAllowed', 'ShouldAllowFreeTravel', 'AfterRoomEntered']},
    'WONGOS_MYSTERY_TICKET': {'value': 3, 'var_type': 'RepeatVar', 'hooks': ['AfterCombatEnd', 'TryModifyRewards', 'AfterModifyingRewards']},
    'YUMMY_COOKIE': {'value': 4, 'var_type': 'CardsVar', 'hooks': ['AfterCloned', 'AfterObtained']},
}